### ISSUE TITLE
Custom logger

### ISSUE THREAD

**Issue by Mondei1** [ch-a-os/DocSort#105]
Just for pretty `info`, `success`, `warn` and `error` messages we need a sick custom logger :smile:. Can used for #78

**Comment by 720degreeLotus** [comment]
We can also implement a setting `enableDebugLogging` and if this is set to true, debug-logs will be printed :)
Such a logger is done easily and so we don't need to implement another npm^^

**Comment by 720degreeLotus** [comment]
Coded some simplistic custom logger, the output can be wasily adjusted afterwards :)

![image](https://user-images.githubusercontent.com/12686187/56392828-d13f8a80-6232-11e9-9bda-afef86e51425.png)
