### ISSUE TITLE
Only select needed fields in getDocumentFile()

### ISSUE THREAD

**Issue by 720degreeLotus** [ch-a-os/DocSort#21]
Only query the fields that are needed to generate the filepath.

**Comment by Mondei1** [comment]
Because this is a small change, we can put this into v0.1.

**Comment by 720degreeLotus** [comment]
Allright

**Comment by Mondei1** [comment]
This change is already done in branch `tag_create_endpoint` for issue #52. Sorry but it was just to small :smile:
