### ISSUE TITLE
EP "getDocumentMeta" still needed?

### ISSUE THREAD

**Issue by 720degreeLotus** [ch-a-os/DocSort#24]
@Mondei1 From my perspective the EP "getDocumentMeta" is no longer needed. Can you tell me your opinion on that, so we can delete it, if it's not needed anymore?

**Comment by Mondei1** [comment]
No, we don't need it anymore. There is the `getDocument` and `getDocuments` EP for it. But I see you already deleted it.

So I can close this issue here...
