### ISSUE TITLE
smooth filedownload on gui

### ISSUE THREAD

**Issue by 720degreeLotus** [ch-a-os/DocSort#35]
I just tested a code-snippet and a filedownload does work very smooth without calling any new site or opening a new tab.
Here is an example-site you can see how it works with JS. I think that in angular there is a much smoother way for this, i just wanted to test if, what we wanted, does work :)

So, just copy-paste this into an html-file, load it and click the "download-file" :)

```html
<html>
	<head>
		<title>test-page</title>
		<script>
		function getFile() {
			// var blob = new Blob(["123"], { type: 'text/html' });
			// blob["lastModifiedDate"] = "";
			// blob["name"] = "filename.html";
			// var fakeF = blob;
			
			// It is necessary to create a new blob object with mime-type explicitly set
			// otherwise only Chrome works like it should
			var newBlob = new Blob(["my content"], {type: "text/plain"})

			// IE doesn't allow using a blob object directly as link href
			// instead it is necessary to use msSaveOrOpenBlob
			if (window.navigator && window.navigator.msSaveOrOpenBlob) {
				window.navigator.msSaveOrOpenBlob(newBlob);
				return;
			} 

			// For other browsers: 
			// Create a link pointing to the ObjectURL containing the blob.
			const data = window.URL.createObjectURL(newBlob);
			var link = document.createElement('a');
			link.href = data;
			link.download="file.txt";
			link.click();
			// For Firefox it is necessary to delay revoking the ObjectURL
			setTimeout(function(){ window.URL.revokeObjectURL(data), 100});
		}
		</script>
	</head>
	<body>
		<h1 onClick="getFile()">download-file</h1>
	</body>
</html>
```

**Comment by Mondei1** [comment]
Is it a good idea to embed plain Javascript code into a Angular application?

**Comment by 720degreeLotus** [comment]
> I think that in angular there is a much smoother way for this, i just wanted to test if, what we wanted, does work :)

**Comment by Mondei1** [comment]
I moved this issue directly in our v.0.1-BETA milestone becasue this should be simple to implement.

**Comment by 720degreeLotus** [comment]
Angular-Example:
https://stackblitz.com/edit/angular-blob-file-download

**Comment by Mondei1** [comment]
Currently not necessary for the release 0.1 so I moved it into v0.x
