### ISSUE TITLE
Search through documents

### ISSUE THREAD

**Issue by 720degreeLotus** [ch-a-os/DocSort#4]
The user should be able to view all documents.
The best way to achieve this is most likely to create a "search documents" page which, per default, shows the last N uploaded documents. In addition, it lets the user filter shown documents by various criteria.

**Comment by 720degreeLotus** [comment]
Since the backend already supports this by the searchDocument-EP, the GUI is the only thing missing an implementation.

**Comment by Mondei1** [comment]
**Status update:** Almost done
