### ISSUE TITLE
Remove default exports

### ISSUE THREAD

**Issue by 720degreeLotus** [ch-a-os/DocSort#43]
@Mondei1 I just thought about this...
We now have many default exports, which allow this:
```js
import extractFileExtension from "../lib/extractFileExtension";
```
which "saves" the `{ }`.
But at the same point, we could, by mistake, name the imported function wrong, because since we are importing a default-export, this is also "allowed":
```js
import someWrongAndIrritatingFunctionName from "../lib/extractFileExtension";
```
And when we are implementing one more function into ""../lib/extractFileExtension", we need to rename ALL import-statements to not mix them up...
I am thinking about maybe better remove the default-exports in most, if not every, exports, what do you think about this?

**Comment by Mondei1** [comment]
I think we can do that. But I generally don't like the idea to put one function into one file with about 20-40 lines of code. Maybe we should move them into related library files. This was why I defaulted them because it was just one function in that file.

**Comment by 720degreeLotus** [comment]
Ok, we can do that. But i would maybe wait a little bit until we do this, because in the meantime there will come more functions that we create and then, at some point, we can group some functions and put them into one file.
Like,, one file for crypto, one file for JWT and so on :)

**Comment by 720degreeLotus** [comment]
Since we discussed this, i removed the questionmark from the title ;)
