### ISSUE TITLE
Check existence of user in middleware

### ISSUE THREAD

**Issue by 720degreeLotus** [ch-a-os/DocSort#45]
In all endpoints we check the existence of the user, regardless of the user-id in the JWT.
```js
const userId = getUserIDFromJWT(req.headers.token.toString());
const user = await User.findOne({ where: { id: userId }});
```
And this is correct, because when the token is valid for 1 day and we delete the user, the user could still access the data for the rest of the day.
In the future we should maybe implement user-management where we can "disable" a user and if that's the case, the user cannot access any data too.

So we should move the checking of the user-existence into a middleware to centralize this check.

**Comment by Mondei1** [comment]
Done with e35779a7817eefb726fc654559bf34943aee8523
