### ISSUE TITLE
Better config-switch for erasing old db on each startup

### ISSUE THREAD

**Issue by 720degreeLotus** [ch-a-os/DocSort#47]
For the future we should use a better way (within the config) to switching on/off erasing of the old db on each startup.

**Comment by Mondei1** [comment]
This is easy because this is just one config entry but maybe we can add later "Developer Options" with this in it. So, an developer can toggle this option right in the frontend idk.

**Comment by 720degreeLotus** [comment]
Also see #53

**Comment by 720degreeLotus** [comment]
Mentioned within #53.

**Comment by Mondei1** [comment]
@720degreeLotus Would open this issue because this issue is not implemented yet. Actually we can add this to #53 too.

**Comment by 720degreeLotus** [comment]
Alright :)
