### ISSUE TITLE
EP: eraseDb

### ISSUE THREAD

**Issue by 720degreeLotus** [ch-a-os/DocSort#48]
Later we need an endpoint for erasing/resetting the whole DB. This can then be triggered from the gui.

**Comment by 720degreeLotus** [comment]
@Mondei1 I think we talked about this.... what was our conclusion? Is this feature needed or not?
I mean, erasing the database withOUT the files, makes no sense.
So we are more talking about a complete resete of the software and... maybe we should embed this into the installer/uninstaller and not make possible in the app itself... What do you think?

**Comment by Mondei1** [comment]
It would be a security mess I think. I think too that we should add this to an uninstaller.

**Comment by 720degreeLotus** [comment]
Closed because we are implementing this into the installer/uninstaller.
