### ISSUE TITLE
refactor: uploadSingleDocument -> givenTags

### ISSUE THREAD

**Issue by 720degreeLotus** [ch-a-os/DocSort#50]

**Comment by Mondei1** [comment]
Can you explain further what you mean? "No description provided." is not very helpful :smile:

**Comment by 720degreeLotus** [comment]
Hmm, i'm not happy about what i coded here:
```typescript
// Setting up TAGs
        const givenTags: Array<string> = uploadDocument.tags_R;
        console.log("Tag:", givenTags)
        if(uploadDocument.tags_R != null) {
            newDocument.tags_R = new Array();
            for (const tag of givenTags) {
                newDocument.tags_R.push(mongoose.Types.ObjectId(tag));
            }
        }
```
Because i think the for-loop is not needed.
We start with an array of strings that contains the objectIDs of all given tags (as strings).
We should be able to accomplish this by using the `map()`-function of ES6 to convert the strings into objectIDs.. and then we can just put the outcome object to `newDocument.tags_R`...
So like this:
```typescript
uploadDocument.tags_R.map(entry=> mongoose.Types.ObjectId(entry)); // this converts the strings to objectIDs
newDocument.tags_R = uploadDocument.tags_R;
```
Must be tested but this should work properly^^
