### ISSUE TITLE
Logging within database / last activity

### ISSUE THREAD

**Issue by 720degreeLotus** [ch-a-os/DocSort#51]
After the first 1.0 release we can think about, if a log-collection within the database would make sense.
It could be used for debugging and error-reporting and/or also for storing the activity of a user...
But i'm not sure about the activity-thing, because from our currently predicted use-case the user would only be interested which last documents he uploaded, or what documents were updated recently... But those 2 cases are already covered by `createdAt` and `updatedAt`... So there maybe is no reason at all to store the activoty and the error-logs could also be stored in just a log-file on the harddrive...
This is just a thought :)

**Comment by Mondei1** [comment]
Maybe this can be added to `Developer options` for debugging reasons but as user this doesn't make any sense to add.

**Comment by 720degreeLotus** [comment]
Yeah.... as i thought. Well, loggin into some debug-txt would be nice regardless of this, so i'm gonna close this issue and if we ever feel the need to implement some debug-log in some txt-file,m we can open a new issue.
