### ISSUE TITLE
Own endpoint for tag creation

### ISSUE THREAD

**Issue by Mondei1** [ch-a-os/DocSort#52]
Idk, I personally don't like the idea to create an tag on upload If not existant. I prefer an own endpoint that the frontend requests when creating an own tag. @720degreeLotus Whats your opinion on it?

**Comment by 720degreeLotus** [comment]
Hmm... i agree that we should create an endpoint for this.
And when we have an EP, we can just create the tags before adding them to a document.
Implementation can be started after the branch `fix_frontend_upload` is merged.

**Comment by Mondei1** [comment]
**Update:** The branch can be merged but I'll wait until @720degreeLotus is done with his branch `rework_separate_tag_creation` for the implementation in the frontend.

**Comment by 720degreeLotus** [comment]
Branch was merged (had to resolve some conflicts manually), should be done now :)
