### ISSUE TITLE
Append first and second number and title to filename on download

### ISSUE THREAD

**Issue by 720degreeLotus** [ch-a-os/DocSort#82]
We should add some UID like the objectId to the filename of a file when it's downloaded.
The user could store multiple documents of the same title in his download-folder and we don't want to overwrite those.
We can/should add the primary and secondary number, like "sql santa_12.2.png".

**Comment by 720degreeLotus** [comment]
I was thinking, maybe put the numbers first, like
`12.2_sql santa.png` and
`31.6_my important document.pdf`.
Also, we should limit the filename because the title itself can be a long text. I would cut the title to a fixed length and add `...` like
`12.1_this document is very important becau...png` or
`12.1_this document is very important becau..._.png`.
I would prefere `12.1_this document is very important becau..._.png` i think...

**Comment by Mondei1** [comment]
It would be better to limit the title length on creation to like 50 characters. But yes, appending the first/second number at the beginning is a good idea.
