### ISSUE TITLE
Keep a Changelog

### ISSUE THREAD

**Issue by Mondei1** [ch-a-os/DocSort#96]
In order to tell the history of DocSort and which features we added, removed, deprecated and so on, we should add a changelog following a simple and strict format. I would use the [Keep a Changelog standard](https://keepachangelog.com/en/1.1.0/). Good example is the [changelog of the Godot Engine](https://github.com/godotengine/godot/blob/master/CHANGELOG.md).

**Comment by 720degreeLotus** [comment]
Finished
